### ISSUE TITLE
Wikidata <-> Evighetsrunor

### ISSUE THREAD

**Issue by salgo60** [uppsala-university/Evighetsrunor#1]
Container för saker mellan Evighetsrunor och Wikidata

* Såg att Wikidata populerades och min tro är att vi bättre skapar en ny egenskap i Wikidata för att slippa otydlighet som finns för Evighetsrunor / Fornsök se [Wikidata förslag](https://www.wikidata.org/wiki/Wikidata:Property_proposal/Evighetsrunor) och kommentera gärna. Jag tror kanske det är även att föredra att direkt koppla Wikidata till Evighetsrunor, underhållet av Ksamsök har tyvärr inte varit det bästa se [diskussion sv:Wikipedia om dom problemen](https://sv.wikipedia.org/wiki/Malldiskussion:BBR-l%C3%A4nk#Anl%C3%A4ggnings-ID_fungerar_inte_i_Lista_%C3%B6ver_byggnadsminnen) 

* FYI Litteraturbanken har en ny applikation för platser i litteraturen där ett antal runstenar tas upp jag pekade på er se deras GITHUB [spraakbanken/littb-frontend/issues/29](https://github.com/spraakbanken/littb-frontend/issues/29)

![image](https://user-images.githubusercontent.com/14206509/107117911-d9404280-687d-11eb-97cd-74296f751b28.png)

**Comment by peterjaric** [comment]
Tack för din input, @salgo60. Du har fått svar på Wikidata, så jag stänger detta ärende!

**Comment by salgo60** [comment]
@peterjaric Fråga: finns det några tankar på dataroundtrip eller hämta hem bilder......??? se nedan vad jag gör skrik till om det blir fel för er.... eller är ointressant för er... är vi riktigt visionära så skapar vi ett schema vad vi vill ha för egenskaper på en bild jmf. det jag gjort vad jag vill se på en runsten som finns hos Litteraturbanken [EntitySchema:E290](https://www.wikidata.org/wiki/EntitySchema:E290)

Jag ser Abbe testade med SPARQL federation en variant som kanske kan ge Evighetsrunor mervärde är att ha mer bilder om era runor från WIkicommons om kvaliten duger.... Jag testar nu att sätta på Bilden vilken runa den avbildar --> att den kan "plockas hem av er" och matchas med sin "runa" rel. enkelt.... snyggast vore om ni hade bildens unika ID i Wikicommons hos er så ser ni rel. snabbt om det är nya bilder eller ej i Wikicommons.... plus gissar jag enklare hålla koll på fel som görs i vår miljö....

**Mitt scope**
1) jag tar dom runor som finns hos Litteraturbanken se [worksheet](https://docs.google.com/spreadsheets/d/1TraXcbQwSsysCfsTK5i0zECVFIw2OoIjRZ0nv64GX-M/edit#gid=0) och ser till att 
1-1) om dom inte finns i Wikidata så skapar jag nya objekt --> blir ung. 2600
1-2) att dom har en koppling till boken hos Litteraturbanken, vilken sida där runan omnämns se [karta](https://w.wiki/zKW) redan kopplade (status 1698 skapade, kvar 911 att skapa, kvar 1600 att koppla till plats i boken

jag har nu även försökt att matcha bild med runa och även börjat lägga in SDC -  Structured Data in Commons 

2-1) på bild med runan säger jag "depict" runans namn (gissar att här borde man fundera över hur man anger om bilden är framifrån, bakifrån, detalj etc.... )

se [video](https://www.youtube.com/watch?v=cL1fJ_kWuW0) 

ex. 
* bild [File:Sö 226, Stutby 1900.jpg](https://commons.wikimedia.org/wiki/File:S%C3%B6_226,_Stutby_1900.jpg)
  * har även id [M14048870](http://commons.wikimedia.org/entity/M14048870) --> json = [M14048870.json](http://commons.wikimedia.org/entity/M14048870.json) 
     där man ser P180 depict [Q7666316](https://www.wikidata.org/wiki/Q7666316) = "Södermanlands runinskrifter 226" 
  
  
![image](https://user-images.githubusercontent.com/14206509/108201997-cac91500-7120-11eb-9beb-4d62902fb4ef.png)

Vet inte status på SPARQL endpointen tror den har en fördröjning se test [SPARQL fråga](https://wcqs-beta.wmflabs.org/embed.html#%23%20runestones%0A%23defaultView%3AImageGrid%0ASELECT%20DISTINCT%20%3Fsignum%20%3Ffile%20%3Fitem%20%3FitemLabel%20%3FitemDescription%20%3Fimage%20%3Fksam%20%3FEvighetsRunor%0AWITH%20%0A%7B%20SELECT%20%3Fitem%20%3FitemLabel%20%3FitemDescription%20%3Fksam%20%3FEvighetsRunor%20%3Fsignum%20WHERE%0A%20%20%7B%20SERVICE%20%3Chttps%3A%2F%2Fquery.wikidata.org%2Fsparql%3E%20%0A%20%20%20%20%7B%3Fitem%20wdt%3AP1261%20%3Fsignum%3B%0A%20%20%20%20%20%20wdt%3AP17%20wd%3AQ34%3B%0A%20%20%20%20%20%20wdt%3AP1260%20%3Fksam.%0A%20%20%20%20%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22sv%2Cen%22.%20%3Fitem%20rdfs%3Alabel%20%3FitemLabel%20.%7D%0A%20%20%20%20%20%20FILTER%28CONTAINS%28%3Fksam%2C%22uu%2Fsrdb%2F%22%29%29%0A%20%20%20%20%20BIND%28URI%28CONCAT%28%22http%3A%2F%2Fkulturarvsdata.se%2F%22%2C%3Fksam%29%29%20AS%20%3FEvighetsRunor%29%0A%23%20uu%2Fsrdb%2Fd2a4ed30-a765-4d8c-82ad-57fe4b293d21%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%20AS%20%25Wikidataitems%0A%0AWHERE%20%0A%7B%20%20INCLUDE%20%25Wikidataitems%20.%0A%20%20%3Ffile%20wdt%3AP180%20%3Fitem.%0A%20%20%23%20This%20is%20a%20hack%20to%20make%20ImageGrid%20work%0A%20%20%3Ffile%20schema%3AcontentUrl%20%3Furl.%20%0A%20%20bind%28iri%28concat%28%22http%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FSpecial%3AFilePath%2F%22%2C%20wikibase%3AdecodeUri%28substr%28str%28%3Furl%29%2C53%29%29%29%29%20AS%20%3Fimage%29%0A%7D%0ALIMIT%201000) 
 
  * visar Signum , Ksamsök id för Evighetsrunor, WD objektet 
![image](https://user-images.githubusercontent.com/14206509/108205934-00bcc800-7126-11eb-917b-8f5d5a7878a0.png)

* samma men som [lista](https://wcqs-beta.wmflabs.org/embed.html#%23%20runestones%0ASELECT%20DISTINCT%20%3Ffile%20%3Fruna%20%3FrunaLabel%20%20%3Fsignum%20%3Fimage%20%3Fksam%20%3FEvighetsRunor%0AWITH%20%0A%7B%20SELECT%20%3Fruna%20%3FrunaLabel%20%3Fsignum%20%3Fksam%20%3FEvighetsRunor%20WHERE%0A%20%20%7B%20SERVICE%20%3Chttps%3A%2F%2Fquery.wikidata.org%2Fsparql%3E%20%0A%20%20%20%20%7B%3Fruna%20wdt%3AP1261%20%3Fsignum%3B%0A%20%20%20%20%20%20wdt%3AP17%20wd%3AQ34%3B%0A%20%20%20%20%20%20wdt%3AP1260%20%3Fksam.%0A%20%20%20%20%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22sv%2Cen%22.%20%3Fruna%20rdfs%3Alabel%20%3FrunaLabel%20.%7D%0A%20%20%20%20%20%20FILTER%28CONTAINS%28%3Fksam%2C%22uu%2Fsrdb%2F%22%29%29%0A%20%20%20%20%20BIND%28URI%28CONCAT%28%22http%3A%2F%2Fkulturarvsdata.se%2F%22%2C%3Fksam%29%29%20AS%20%3FEvighetsRunor%29%0A%23%20uu%2Fsrdb%2Fd2a4ed30-a765-4d8c-82ad-57fe4b293d21%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%20AS%20%25Wikidataitems%0A%0AWHERE%20%0A%7B%20%20INCLUDE%20%25Wikidataitems%20.%0A%20%20%3Ffile%20wdt%3AP180%20%3Fruna.%0A%20%20%23%20This%20is%20a%20hack%20to%20make%20ImageGrid%20work%0A%20%20%3Ffile%20schema%3AcontentUrl%20%3Furl.%20%0A%20%20bind%28iri%28concat%28%22http%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FSpecial%3AFilePath%2F%22%2C%20wikibase%3AdecodeUri%28substr%28str%28%3Furl%29%2C53%29%29%29%29%20AS%20%3Fimage%29%0A%7D%0ALIMIT%201000)

![image](https://user-images.githubusercontent.com/14206509/108206741-167ebd00-7127-11eb-98b0-b5b949a83db0.png)


* här skulle man kunna tänka sig att ha en Evighetsrunor egenskap i WIkidata som håller redan på det unika bildid som ni har  i Evighetsrunor... vi har det för Digitaltmuseum i egenskap [Property:P7847](https://www.wikidata.org/wiki/Property:P7847) där det är deras id på en container som innehåller bilden (funkar men kunde varit bättre)
 
cc: @carwash 

UPDATE: SPARQL på commons ligger inte i fas med Wikicomons --> gissar att nästa vecka kommer vi att hitta mer se

![image](https://user-images.githubusercontent.com/14206509/108223779-73d03980-713a-11eb-9baa-1a4791518781.png)

**Comment by peterjaric** [comment]
Hej Magnus!

WikiCommons och SPARQL är inte riktigt inom scope för APIerna som erbjuds av Samnordisk runtextdatabas, så jag kan tyvärr inte svara på din fråga. Ska jag vara helt ärlig så har jag inte förkunskaper nog att förstå den fullt ut. 

Jag skulle gissa på att den här diskussionen kanske inte hör hemma precis här. Vi använder det här repot först och främst som en hemvist för specifikationen för runtextdatabasens REST-API och det ursprungliga tillståndet för databasen.

Jag ser att du har cc:at @carwash, kanske kan han komma med någon kommentar.

**Comment by salgo60** [comment]
Skrik till om du har frågor 070-5937579.....

Min tanke är bara att om kvaliten duger så finns det en hel del bilder att lägga upp hos er från Wikicommons.... gick igenom [Södermanland och där finns flera 100 bilder](https://commons.wikimedia.org/wiki/Category:Runestones_in_S%C3%B6dermanland). Jag kopplar på metadata just nu på bilderna se [video](https://youtu.be/vgB5rvF57bE) --> denna koppling blir enklare för er och troligen syns dom i SPARQL frågan nästa vecka....

Jag tror inte det skall vara några licens problem men det verkar även finnas licensen i metadata på bilderna.... 

* om [Structured data in Commons](https://www.youtube.com/watch?v=lmWmMIuCJVM) dvs. att ha metadata om bilden 
* [video](https://youtu.be/vgB5rvF57bE) hur jag med ett verktyg [User:Magnus Manske/sdc_tool.js](https://commons.wikimedia.org/wiki/User_talk:Magnus_Manske/sdc_tool.js) från Magnus Manske lägger tikk metadata om motivet för alla bilder i en kategori
* [video](https://youtu.be/yfvsM4nac-s) hur jag kör [Open Refine](https://openrefine.org/) för att städa datat innan det åker in i Wikidata 

Verktyget ovan. aktiveras genom att ha på Wikicommons följande rad jmf min [commons.js](https://commons.wikimedia.org/wiki/User:Salgo60/common.js) 
  
> importScript('User:Magnus Manske/sdc_tool.js') ;

**Comment by peterjaric** [comment]
Hej igen Magnus!

Som sagt, vi hanterar inte WikiCommons eller ens bilder inom ramarna för det här Github-projektet. Jag vet inte riktigt vart du ska vända dig, men här kommer tyvärr inte dina ansträngningar till någon nytta.

Hoppas du hittar rätt person att prata med!

**Comment by salgo60** [comment]
Ok kändes bara som dom kunde ge mervärde... jag har inget personligt intresse att det dyker upp bilder på Evighetsrunor jag är mer intresserad av bra metadata och att det vore kul att ha en fungerande metadata roundtrip och lära sig vad som kan gå fel....  i mitt tidigare liv gjorde vi metadataroundtrip men då var det internationella penningtransaktioner så det gjorde lite mera ont om det blev fel ;-)

Nu vet ni att metadata finns på en hel del bilder så det är enklare att plocka hem det som duger om andan faller på... om jag fatta rätt så skulle det hämtas/kopplas från Alvin....

**Comment by carwash** [comment]
Som du säkert minns från vår presentation vid Runors lansering har vi för avsikt att även visa bilder från Wikimedia Commons på Runorgränssnittet i framtiden. Planen började med att helt enkelt utnyttja länkarna som Commons bidrar till UGC-hubben, men nu att det finns structured data på Commons och tätare integration mot Wikidata vore det såklart effektivt att även ta del av detta för att hitta bilder genom matchande URI:er på Wikidata/Commons. Det skulle definitivt ge mervärde, och har funnits med i vår planering redan från början – på den punkten är vi överens. :)
Som Peter påpekar, det här repot är till för SRDB-API:et hos UU; frågor om Runor-gränssnittet hör inte riktigt hemma här.

**Comment by salgo60** [comment]
Plocka hem de bilderna som är bra nog och har rätt licens skulle jag göra... saknar många gånger bilder på de runor jag checkat i appen.... problemet jag ser med SDC är att få använder det men det blir säkert bättre med tiden jag försöker köra igenom dom 2400 runor som finns i böckerna från [Vitterhetsakademin](https://litteraturbanken.se/f%C3%B6rfattare/KVHAA/titlar) 

Sedan ha koll på dom unika id:n för de bilder ni hämtat och de bilder som inte har rätt kvalitet... tror jag är en bra tanke om ni skall ha dataround tripping....

* sorry har inget minne av presentationen och era planer men dela gärna om det finns planer/specar... jag hoppas vara klar med Litteraturbanken och bilderna nästa vecka så sedan blir det lungt ;-)

**Comment by salgo60** [comment]
[Description of dataroundtripping WD <-> RAÄ](https://meta.wikimedia.org/wiki/Structured_data_for_GLAM-Wiki/Roundtripping/KMB) if you have plans to share if this will be used in Evighetsrunor please do?

![image](https://user-images.githubusercontent.com/14206509/112712251-7575e580-8ece-11eb-876c-ef678165f6bb.png)
![image](https://user-images.githubusercontent.com/14206509/112712262-89214c00-8ece-11eb-8aeb-11d5cbd9f704.png)

* mer kopplingar [Wikidata Litteraturbanken och övriga källor](https://github.com/salgo60/Litteraturbanken_wd_runes/tree/main)
   * karta med [alla källor vi har kopplade](https://query.wikidata.org/embed.html#%23defaultView%3AMap%7B%22hide%22%3A%5B%22%3Fcoord%22%5D%2C%20%22layer%22%3A%20%22%3FcitationLabel%22%7D%0ASELECT%20distinct%20%3Fitem%20%3FitemLabel%20%3FcitationLabel%20%3Fpage%20%20%3FLitteraturbanken%20%20%20%3FitemDescription%20%3Fcoord%20%20%3Fimg%20%3Fsignum%20%3Fsound%20%3Furl%20%3Ftitle%20WHERE%20%7B%0A%20%20%20VALUES%20%3Finstance%20%7B%0A%20%20wd%3AQ24566025%20%23Runesten%0A%20%20wd%3AQ7379880%20%20%23Runinsctiption%0A%20%20%7D.%0A%20%20%3Fitem%20wdt%3AP31%20%3Finstance.%0A%20%20OPTIONAL%20%7B%3Fitem%20wdt%3AP18%20%3Fimg%7D.%0A%20%20OPTIONAL%20%7B%3Fitem%20wdt%3AP1261%20%3Fsignum%7D.%0A%0A%20%20%3Fitem%20wdt%3AP625%20%3Fcoord.%0A%20%20%3Fitem%20p%3AP1343%20%3FPDescribedBy%3B%0A%20%20%20%20%20%20%20%20%20%3FLitt%20%3FLitt_value%20.%0A%20%20%20%20%3FLitt_value%20prov%3AwasDerivedFrom%20%3Freference%20.%0A%20%20%20%20%3Freference%20pr%3AP248%20%3Fcitation%20.%20%0A%20%20%20%20OPTIONAL%20%7B%3Freference%20pr%3AP5123%20%3Flitturl%20%7D%20%0A%20%20%20%20OPTIONAL%20%7B%3Freference%20pr%3AP854%20%3Furl%20%7D%20%0A%20%20%20%20OPTIONAL%20%7B%3Freference%20pr%3AP953%20%3Furl%20%7D%20%0A%20%20%20%20OPTIONAL%20%7B%3Freference%20pr%3AP1476%20%3Ftitle%20%7D%20%0A%20%20%20%20OPTIONAL%20%7B%3Freference%20pr%3AP1810%20%3Ftitle%20%7D%20%0A%20%20%20%20BIND(URI(CONCAT(%22https%3A%2F%2Flitteraturbanken.se%2Fforfattare%2F%22%2C%3Flitturl))%20AS%20%3Furl)%0A%20%20%20%20OPTIONAL%20%7B%3Freference%20pr%3AP304%20%3Fpg%7D%20.%0A%20%20%20%20BIND(CONCAT(%22Sida%20%22%2C%3Fpg)%20AS%20%3Fpage)%0A%0A%20%20%23%20Soundfile%0A%20%20OPTIONAL%7B%3Fitem%20wdt%3AP443%20%3Fsound.%20%7D%0A%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22sv%2Cen%22.%20%7D%0A%7D%20order%20by%20%3FcitationLabel) till WIkidata 

<img width="1184" height="851" alt="Image" src="https://github.com/user-attachments/assets/88f5c74b-3e30-4ed5-9a9b-ddfb23ef5b4a" />
